#PARA UTILIZAR ESSES ENDPOINTS É NECESSÁRIO INSTALAR A EXTENSÃO DO VSCODE "REST CLIENT"
###

GET http://localhost:3333/Funcionarios

###

POST http://localhost:3333/Funcionarios
Content-Type: application/json

{
    "name": "Julio lanches",
    "senha": "São Paulo"
}

###

PUT http://localhost:3333/Funcionarios/b94e5a0f-b71a-4dfd-a169-c574c3f41127
Content-Type: application/json

{
   "name": "Julio laaaaaaaaahes",
    "senha": "Saaaaaaaaaao"
}

###

DELETE http://localhost:3333/Funcionarios/54cdaa96-af83-43e3-84f9-89f73f353d86
