#PARA UTILIZAR ESSES ENDPOINTS É NECESSÁRIO INSTALAR A EXTENSÃO DO VSCODE "REST CLIENT"
###

GET http://localhost:3333/Funcionarios

###

POST http://localhost:3333/Funcionarios
Content-Type: application/json

{
    "name": "Julio lanches",
    "senha": "São Paulo"
}

###

PUT http://localhost:3333/Funcionarios/b23f8129-1483-4bac-9f4c-4ffcb5011506
Content-Type: application/json

{
   "name": "Julio laaaaaaaaahes",
    "senha": "Saaaaaaaaaao"
}

###

DELETE http://localhost:3333/Funcionarios/b23f8129-1483-4bac-9f4c-4ffcb5011506

###




                // ENDPOINTS ENTRADA E SAIDA
GET http://localhost:3333/entradasaida

###

POST http://localhost:3333/entradasaida
Content-Type: application/json

{
    "name": "Maria Julia",
    "date": "2006-12-10"
}

###

PUT http://localhost:3333/entradasaida/6a8f353c-d172-4997-9601-069014308358
Content-Type: application/json

{
   "name": "Maria Fernanda",
    "date": "12/10/2024"
}

###

DELETE http://localhost:3333/entradasaida/b23f8129-1483-4bac-9f4c-4ffcb5011506