#PARA UTILIZAR ESSES ENDPOINTS É NECESSÁRIO INSTALAR A EXTENSÃO DO VSCODE "REST CLIENT"
###

GET http://localhost:3333/Funcionarios

###

POST http://localhost:3333/Funcionarios
Content-Type: application/json

{
    "name": " ",
    "senha": " "
}

###

PUT http://localhost:3333/Funcionarios/#
Content-Type: application/json

{
   "name": " ",
    "senha": " "
}

###

DELETE http://localhost:3333/Funcionarios/d87d2f02-aa5c-41d4-9cca-b901000d8620

###




                // ENDPOINTS ENTRADA E SAIDA
GET http://localhost:3333/entradasaida

###

POST http://localhost:3333/entradasaida
Content-Type: application/json

{
    "name": " ",

}

###

PUT http://localhost:3333/entradasaida/d98fd6f4-8210-4291-924a-d1d83a7f5bba
Content-Type: application/json

{
   "name": " ",
}

###

DELETE http://localhost:3333/entradasaida/#